// Mocks generated by Mockito 5.4.6 from annotations
// in track_app/test/repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:track_app/features/auth/data/models/user_model.dart' as _i4;
import 'package:track_app/features/auth/data/repositories/user_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> createUser(_i4.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.UserModel?> getUser(String? userId) =>
      (super.noSuchMethod(Invocation.method(#getUser, [userId]), returnValue: _i3.Future<_i4.UserModel?>.value()) as _i3.Future<_i4.UserModel?>);

  @override
  _i3.Future<void> updateUser(_i4.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<_i4.UserModel?> userChanges(String? userId) =>
      (super.noSuchMethod(Invocation.method(#userChanges, [userId]), returnValue: _i3.Stream<_i4.UserModel?>.empty()) as _i3.Stream<_i4.UserModel?>);

  @override
  _i3.Future<List<_i4.UserModel>> getUsersByRole(String? role) =>
      (super.noSuchMethod(Invocation.method(#getUsersByRole, [role]), returnValue: _i3.Future<List<_i4.UserModel>>.value(<_i4.UserModel>[]))
          as _i3.Future<List<_i4.UserModel>>);

  @override
  _i3.Future<List<_i4.UserModel>> getAllUsers() =>
      (super.noSuchMethod(Invocation.method(#getAllUsers, []), returnValue: _i3.Future<List<_i4.UserModel>>.value(<_i4.UserModel>[]))
          as _i3.Future<List<_i4.UserModel>>);

  @override
  _i3.Future<void> linkParentToChild(String? parentId, String? childId) =>
      (super.noSuchMethod(
            Invocation.method(#linkParentToChild, [parentId, childId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
