// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9qEG2jvVuo3l10B-pQ5Qrnkez-ukvskA',
    appId: '1:727719526685:web:ed9dd467a07d8b778fa1f4',
    messagingSenderId: '727719526685',
    projectId: 'track-app-project',
    authDomain: 'track-app-project.firebaseapp.com',
    storageBucket: 'track-app-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbpfTa50JoQgwVGjIDvbGgQO2MXAHQBm4',
    appId: '1:727719526685:android:b6140b6d8696934d8fa1f4',
    messagingSenderId: '727719526685',
    projectId: 'track-app-project',
    storageBucket: 'track-app-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVIroNncoWmLyutKi6I4l6VjBnZD97Mjg',
    appId: '1:727719526685:ios:c05c4f9c2baa5a758fa1f4',
    messagingSenderId: '727719526685',
    projectId: 'track-app-project',
    storageBucket: 'track-app-project.firebasestorage.app',
    iosBundleId: 'com.example.trackApp',
  );
}
